### ISSUE TITLE
Will this pipeline support timsTOF data?

### ISSUE THREAD

**Issue by PatrickvanZalm** [bigbio/quantms#217]
### Description of feature

Hi Yasset,

Big fan of the work you're putting out there with regards to standardizing next flow pipelines for proteomics data!!

I do wonder, will timsTOF data be supported in the future?

**Comment by PatrickvanZalm** [comment]
Just saw this: https://github.com/bigbio/quantms/issues/191

Anyway, if you're in need of some timsTOF data let me know, I can make some available to you.

**Comment by ypriverol** [comment]
We are working on timsTOF data, However to be fully cloud supported we need a container to work with timTOFF data, here the issue https://github.com/gtluu/timsconvert/issues/29 but nothing yet get done. As soon as we manage to progress here, I will go back to this issue.

**Comment by jpfeuffer** [comment]
@ypriverol does the DIA branch via DIA-NN support timsTOF already? I think we just need to skip the mzML conversion there. Might interfere with our mzML parsing for QC though.

But DDA timsTOF might take a little bit. We need to see if conversion is even viable due to the large amount of data. Otherwise, we need to use raw parsers everywhere and we might get into licensing troubles.

It is definitely on our list.

**Comment by ypriverol** [comment]
As you said, It is in our list. I have spoken with Vadim about this and DIA - timTOFF is not based on mzMLs, then we may have issues in the QC part.

**Comment by ypriverol** [comment]
Dear @PatrickvanZalm we are now supporting TimTOFF data, please check the latest release.
