### ISSUE TITLE
proteomicsLFQ with new SVM results in UPS1 dataset 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#301]
### Description of feature

@timosachsenberg @jpfeuffer @daichengxin we also have run it with parameters: 

```
feature_with_id_min_score = 0.25
feature_without_id_min_score = 0.75
```

Dataset PXD001819, Files: http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/quantms-benchmark/PXD001819NEWSAGE/

Results Table: 

![image (7)](https://github.com/bigbio/quantms/assets/52113/0612b937-7f7b-46cb-85bf-fdd7e694f445)

Previous UPS detected: 

![image (8)](https://github.com/bigbio/quantms/assets/52113/5e5835c9-0ce5-43a6-af7b-1cca4f7b03fb)

Current UPS detected: 

![image (9)](https://github.com/bigbio/quantms/assets/52113/d2182491-fade-4362-8e4e-af4c863ec2d3)

This issue needs to be discussion about the default parameters for MBRs. This issue is related to #287

**Comment by ypriverol** [comment]
@daichengxin can you provide a similar plot than the last one for Maxquant.

**Comment by timosachsenberg** [comment]
I think the numbers don't tell you that much here. Can we somehow see how well the quantities match? e.g., if we only picked up noise in the old version the new one would be better. (and the other way around)

**Comment by ypriverol** [comment]
You are right, this is why I ask for the same plot from MQ for the last plot. Our first version of the plot has a lot of noise quantities, and we have solved that, but we have to find the right parameters for both thresholds now. It looks like the current 0.25 and 0.75 is too stringent by the results in here #287

**Comment by jpfeuffer** [comment]
I agree. Can we do an automated evaluation maybe? We could even do a little step in nextflow and then launch the process multiple times with different parameters.

**Comment by jpfeuffer** [comment]
But from my memory this actually looks a bit like the MQ results.

Except for the lowest concentration of course. In theory it does not make sense that you find more features in lower concentrations, if you didn't even find them in higher ones.

**Comment by daichengxin** [comment]
MaxQuant results provided by original paper : [PalombaA_pubmed_34038140_2.xlsx](https://github.com/bigbio/quantms/files/12837872/PalombaA_pubmed_34038140_2.xlsx)

**Comment by daichengxin** [comment]
The same plot given by authors. https://europepmc.org/articles/PMC8280745/figure/fig2/
![image](https://github.com/bigbio/quantms/assets/37200167/c6806cec-c081-40fb-915b-15c2f4d02669)

**Comment by daichengxin** [comment]
0.1&0.9 results. Results folder: http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/quantms-benchmark/PXD001819NEWSAGE/proteomicslfq/
![image](https://github.com/bigbio/quantms/assets/37200167/0e4f41a1-6296-4d4d-9403-3cae213f30e7)
![image](https://github.com/bigbio/quantms/assets/37200167/3ff401f0-0cfb-40fc-874d-1cc60db6595a)

**Comment by jpfeuffer** [comment]
Can you replace P1 and P9 with something reasonable that includes the amol concentration in the header of the MQ xlsx?

**Comment by ypriverol** [comment]
> Test results. Results folder: http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/quantms-benchmark/PXD001819NEWSAGE/proteomicslfq/ ![image](https://user-images.githubusercontent.com/37200167/274262870-031d510d-50a4-43a0-94ef-6fb80221f616.png) ![image](https://user-images.githubusercontent.com/37200167/273396068-3ff401f0-0cfb-40fc-874d-1cc60db6595a.png) ![image](https://user-images.githubusercontent.com/37200167/274262945-a992f4ea-71fd-4be2-b189-b5d6bfdb7bc1.png)

@timosachsenberg @jpfeuffer for the 0.10 and 0.75 I used the threshold of 1000 for the intensity. It actually looks much better than 0.1 0.9 with intensity 10'000. What do you think?

**Comment by jpfeuffer** [comment]
Yes looks better imo. But we should really check expected fold changes.

**Comment by jpfeuffer** [comment]
[upsReval.zip](https://github.com/bigbio/quantms/files/12870050/upsReval.zip)

Here is my old script. In the beginning it includes some fixes for MSstats loading and plotting which are probably not necessary anymore.
I am not sure when I will get to it. Maybe Friday.

**Comment by ypriverol** [comment]
I will try to make it run today and let you know. Do you have the original figures from MQ.

**Comment by jpfeuffer** [comment]
It can read MQ files and PD files, too. I use the results from https://github.com/wombat-p

**Comment by ypriverol** [comment]
Can you provide me a direct link to those outputs PD and MQ from wombat-p. Im now configuring your script.

**Comment by ypriverol** [comment]
Here the results @jpfeuffer of your script with this data: 

![plot_zoom_png](https://github.com/bigbio/quantms/assets/52113/2778ad86-6718-4cb1-baa2-ddbe9a4aba2f)

**Comment by jpfeuffer** [comment]
Looks good but I think not a large improvement to fold changes for comparisons with <=500 amol.

**Comment by ypriverol** [comment]
We are find with that, I have the feeling we have reduced a lot the false positive signals in MBR and that is the major advantage. But as you said nothing has happens in terms of the feature detection by itself in the low concentrations.

**Comment by jpfeuffer** [comment]
I agree that it might be enough since the fold changes did not get worse but the number of found features look a bit better. I think MQ identified way less in the lower concentrations (which doesn't mean much since they might actually be close to unquantifiability).
I am not sure if my MQ files are the best to use (old version and I don't know the settings used) but I can send them tomorrow.

It would be great if we could have some  debug output on all traces of all features across a consensusFeature. Or the extracted areas.
@timosachsenberg we could also check the interpolation of quantities for traces that could not be fit (in the OpenSwath algos). I think you fixed something there but maybe this approach in general is not so great for our purpose?

**Comment by ypriverol** [comment]
I will close the following issue in favor of #303 Please move the discussions about future improvements about MBR LFQ to that issue.

**Comment by jpfeuffer** [comment]
@ypriverol @timosachsenberg This was my old plot for MQ. I don't remember the version. But you can clearly see that *if* MQ finds a feature it is usually correct in rel. quants. We have more proteins basically everywhere, but out quants are very off in the low concentrations. My interpretation is a significant overestimation of quants in features in lower concentrations. Basically starting from 2500 and below there is no difference in quants for a linked feature anymore.
FDR might help but maybe also a more sensitive quantification is necessary in those low concentration features (since as you can see MQ is able to recover 3-4 proteins with correct rel. quants.
![MQ_final](https://github.com/bigbio/quantms/assets/8102638/4c5f23ad-19fc-41e8-baf7-8a8d12a7bf08)

**Comment by timosachsenberg** [comment]
@jpfeuffer do you think the interpolation you mentioned could be an issue? could be easy to check...
